# Generated by Django 5.2.1 on 2025-11-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="تاریخ ایجاد"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_type",
            field=models.CharField(
                choices=[("cash", "نقدی"), ("check", "چکی")],
                default="cash",
                max_length=20,
                verbose_name="نوع پرداخت",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="تاریخ به روزرسانی"
            ),
        ),
    ]
