# Generated by Django 5.2.1 on 2025-11-22 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_created_at_order_payment_type_order_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="quantity",
        ),
    ]
