# Generated by Django 5.2.1 on 2025-11-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_remove_orderitem_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=12, verbose_name="مبلغ کل"
            ),
        ),
    ]
