# Generated by Django 5.2.1 on 2025-11-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_product_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="package_quantity",
        ),
        migrations.RemoveField(
            model_name="product",
            name="stock_quantity",
        ),
        migrations.AddField(
            model_name="product",
            name="is_stock",
            field=models.BooleanField(default=True, verbose_name="موجود در انبار"),
        ),
    ]
