# Generated by Django 5.2.1 on 2025-11-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_remove_contact_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="is_read",
            field=models.BooleanField(default=False, verbose_name="خوانده شده"),
        ),
    ]
