from .users_serializer import UserManagementSerializer, AddressSerializer, UserDetailSerializer
from .products_serializer import ProductManagementSerializer, ProductImageSerializer
from .cars_serializer import CarManagementSerializer
from .categories_serializer import CategoryManagementSerializer
from .orders_serializer import OrderManagementSerializer
from .payments_serializer import PaymentManagementSerializer
from .contacts_serializer import ContactManagementSerializer
from .banner_serializer import BannerManagementSerializer
from .index_serializer import DashboardSerializer