# Generated by Django 5.2.7 on 2025-11-04 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("make", models.CharField(max_length=50, verbose_name="برند خودرو")),
                ("model", models.CharField(max_length=50, verbose_name="مدل خودرو")),
                ("year", models.IntegerField(verbose_name="سال ساخت")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به روزرسانی"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cars",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "خودرو",
                "verbose_name_plural": "خودروها",
                "unique_together": {("make", "model", "year")},
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="نام دسته\u200cبندی"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="shop.category",
                        verbose_name="دسته\u200cبندی والد",
                    ),
                ),
            ],
            options={
                "verbose_name": "دسته\u200cبندی",
                "verbose_name_plural": "دسته\u200cبندی\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام قطعه")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "part_code",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="کد قطعه"
                    ),
                ),
                ("brand", models.CharField(max_length=100, verbose_name="برند")),
                (
                    "country_of_origin",
                    models.CharField(max_length=100, verbose_name="کشور سازنده"),
                ),
                (
                    "warranty",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="ضمانت"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="قیمت"
                    ),
                ),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(default=0, verbose_name="تعداد موجودی"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="shop.category",
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
                (
                    "compatible_cars",
                    models.ManyToManyField(
                        related_name="parts",
                        to="shop.car",
                        verbose_name="خودروهای سازگار",
                    ),
                ),
            ],
            options={
                "verbose_name": "محصول",
                "verbose_name_plural": "محصولات",
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="products/", verbose_name="تصویر"),
                ),
                (
                    "is_main",
                    models.BooleanField(default=False, verbose_name="تصویر اصلی"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به روزرسانی"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="shop.product",
                        verbose_name="محصول",
                    ),
                ),
            ],
        ),
    ]
