# Generated by Django 5.2.7 on 2025-11-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="allow_individual_sale",
            field=models.BooleanField(default=True, verbose_name="امکان فروش تکی"),
        ),
        migrations.AddField(
            model_name="product",
            name="package_quantity",
            field=models.PositiveIntegerField(
                default=1, verbose_name="تعداد در هر بسته"
            ),
        ),
    ]
