# Generated by Django 5.2.1 on 2025-11-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                decimal_places=0, default=1, max_digits=12, verbose_name="مبلغ"
            ),
            preserve_default=False,
        ),
    ]
